baseURL = 'https://shuffzord.github.io'
languageCode = 'en-us'
title = 'Principles'
theme = "hello-friend-ng"
disqusShortname = 'https-shuffzord-github-io'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  enableThemeToggle = true
  # Subtitle for home
  homeSubtitle = "Structure in life"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Principles"
  keywords = "homepage, blog"
  images = [""]


# Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = ["css/math.css"]
  customJS  = []

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Principles"
    subtitle = "Structure in life"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Principles"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[[menu.main]]
    identifier = "Stock"
    name       = "Giełda"
    url        = "/Stock"

[[menu.main]]
    identifier = "Study"
    name       = "Nauka"
    url        = "/Study"

[[menu.main]]
    identifier = "Quote"
    name       = "Cytaty"
    url        = "/Quotes"