name: Daily Stock Reports Generation and Deployment

# Schedule to run daily at 6:00 UTC (after market close)
# Also allow manual triggering for testing and immediate updates
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  workflow_dispatch:  # Allow manual triggering

# Set permissions for the workflow
permissions:
  contents: write  # Allow pushing changes back to repo
  pages: write     # Allow deployment to GitHub Pages
  id-token: write  # Required for GitHub Pages deployment
  actions: read    # Allow reading workflow status

# Prevent concurrent runs to avoid conflicts
concurrency:
  group: "stock-reports"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Include Hugo theme submodules
          fetch-depth: 0         # Full history for Hugo
          token: ${{ secrets.GH_PAT }}

      # Step 2: Verify submodule existence
      - name: Verify StockStrategiest submodule
        run: |
          if [ ! -d "StockStrategiest" ]; then
            echo "Submodule StockStrategiest not found!"
            exit 1
          fi

      # Step 3: Set up Python 3.11 environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Cache pip dependencies for faster builds

      # Step 4: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r StockStrategiest/requirements.txt

      # Step 5: Clean up old reports
      - name: Clean up old reports
        run: |
          rm -rf static/reports/*

      # Step 6: Generate stock reports
      - name: Generate stock reports
        run: |
          cd StockStrategiest
          python report_generator.py --all --fetch-fresh
          cd ..
        env:
          # Add any environment variables needed for report generation
          PYTHONPATH: ${{ github.workspace }}/StockStrategiest

      # Step 7: Process reports for Hugo
      - name: Copy reports for Hugo
        run: |
          python scripts/copy-reports.py

      # Step 8: Commit changes
      - name: Commit changes
        run: |
          git add data/. static/reports/
          git commit -m "Update stock reports - $(date)" || echo "No changes"
          git push
